# fly.toml app configuration file generated for instantdmvnc-backend on 2025-04-11T03:26:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'instantdmvnc-backend'
primary_region = 'iad'

[build]

[http_service]
internal_port = 8675
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
cpu_kind = "performance"
cpus = 2
memory = "2gb"
memory_mb = 2048
